# Generated by Django 4.0.4 on 2022-06-16 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('classe', models.CharField(max_length=50)),
                ('razza', models.CharField(max_length=50)),
                ('allineamento', models.CharField(max_length=50)),
                ('esperienza', models.IntegerField()),
                ('descrizione_fisica', models.CharField(max_length=500)),
                ('descrizione_personalità', models.CharField(max_length=500)),
                ('Hp', models.IntegerField()),
                ('AC', models.IntegerField()),
                ('Initiative', models.IntegerField()),
                ('Speed', models.IntegerField()),
                ('passivePerception', models.IntegerField()),
                ('proficientyBonus', models.IntegerField()),
                ('HitDice', models.IntegerField()),
                ('strenght', models.IntegerField()),
                ('dexterity', models.IntegerField()),
                ('constitution', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('wisdom', models.IntegerField()),
                ('charisma', models.IntegerField()),
                ('acrobatics', models.IntegerField()),
                ('medicine', models.IntegerField()),
                ('animalHandling', models.IntegerField()),
                ('nature', models.IntegerField()),
                ('arcana', models.IntegerField()),
                ('perception', models.IntegerField()),
                ('athletics', models.IntegerField()),
                ('performance', models.IntegerField()),
                ('deception', models.IntegerField()),
                ('persuasion', models.IntegerField()),
                ('history', models.IntegerField()),
                ('religion', models.IntegerField()),
                ('insight', models.IntegerField()),
                ('sleightOfHand', models.IntegerField()),
                ('intimidation', models.IntegerField()),
                ('stealth', models.IntegerField()),
                ('investigation', models.IntegerField()),
                ('survival', models.IntegerField()),
                ('feats', models.CharField(max_length=500)),
                ('armor', models.CharField(max_length=500)),
                ('weapons', models.CharField(max_length=500)),
                ('equipment', models.CharField(max_length=500)),
                ('CP', models.IntegerField()),
                ('SP', models.IntegerField()),
                ('EP', models.IntegerField()),
                ('GP', models.IntegerField()),
                ('PP', models.IntegerField()),
                ('SpellSlots1', models.IntegerField()),
                ('SpellSlots2', models.IntegerField()),
                ('SpellSlots3', models.IntegerField()),
                ('SpellSlots4', models.IntegerField()),
                ('SpellSlots5', models.IntegerField()),
                ('SpellSlots6', models.IntegerField()),
                ('SpellSlots7', models.IntegerField()),
                ('SpellSlots8', models.IntegerField()),
                ('SpellSlots9', models.IntegerField()),
                ('spells', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
