# Generated by Django 4.0.4 on 2022-06-28 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='descrizione_fisica',
            new_name='fisical_description',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='allineamento',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='descrizione_personalità',
            new_name='personality_traits',
        ),
        migrations.RemoveField(
            model_name='character',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='character',
            name='esperienza',
        ),
        migrations.RemoveField(
            model_name='character',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='character',
            name='razza',
        ),
        migrations.AddField(
            model_name='character',
            name='alignment',
            field=models.IntegerField(choices=[(0, 'Lawful Good'), (1, 'Neutral Good'), (2, 'Chaotic Good'), (3, 'Lawful Neutral'), (4, 'True Neutral'), (5, 'Chaotic Neutral'), (6, 'Lawful Evil'), (7, 'Neutral Evil'), (8, 'Chaotic Evil')], default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='clss',
            field=models.IntegerField(choices=[(0, 'Barbarian'), (1, 'Bard'), (2, 'Cleric'), (3, 'Druid'), (4, 'Fighter'), (5, 'Monk'), (6, 'Paladin'), (7, 'Ranger'), (8, 'Rogue'), (9, 'Sorcerer'), (10, 'Warlock'), (11, 'Wizard')], default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='exp',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(450000)]),
        ),
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.IntegerField(choices=[(0, 'Dwarf'), (1, 'Elf'), (2, 'Halfling'), (3, 'Human'), (4, 'Dragonborn'), (5, 'Gnome'), (6, 'Half-Elf'), (7, 'Half-Orc'), (8, 'Tiefling')], default=False),
        ),
        migrations.AlterField(
            model_name='character',
            name='CP',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='EP',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='GP',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='PP',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='SP',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='charisma',
            field=models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='constitution',
            field=models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='dexterity',
            field=models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='intelligence',
            field=models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='strenght',
            field=models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='wisdom',
            field=models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
