# Generated by Django 4.0.4 on 2022-06-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_remove_character_exp_alter_character_clss_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='HitDice',
        ),
        migrations.RemoveField(
            model_name='character',
            name='SpellSlots1',
        ),
        migrations.RemoveField(
            model_name='character',
            name='SpellSlots2',
        ),
        migrations.RemoveField(
            model_name='character',
            name='SpellSlots3',
        ),
        migrations.RemoveField(
            model_name='character',
            name='SpellSlots4',
        ),
        migrations.RemoveField(
            model_name='character',
            name='SpellSlots5',
        ),
        migrations.RemoveField(
            model_name='character',
            name='SpellSlots6',
        ),
        migrations.RemoveField(
            model_name='character',
            name='SpellSlots7',
        ),
        migrations.RemoveField(
            model_name='character',
            name='SpellSlots8',
        ),
        migrations.RemoveField(
            model_name='character',
            name='SpellSlots9',
        ),
        migrations.RemoveField(
            model_name='character',
            name='spells',
        ),
        migrations.AlterField(
            model_name='character',
            name='Speed',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='character',
            name='armor',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='equipment',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='feats',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='fisical_description',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='personality_traits',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='weapons',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
