# Generated by Django 4.0.4 on 2022-06-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_character_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='saving_charisma',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='saving_constitution',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='saving_dexterity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='saving_intelligence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='saving_strenght',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='saving_wisdom',
            field=models.IntegerField(default=0),
        ),
    ]
