# Generated by Django 4.0.4 on 2022-06-30 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0007_character_saving_charisma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='img',
            field=models.ImageField(blank=True, default='images/download.png', upload_to='images/'),
        ),
        migrations.CreateModel(
            name='Proficiencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saving_strenght', models.BooleanField(default=None)),
                ('saving_dexterity', models.BooleanField(default=None)),
                ('saving_constitution', models.BooleanField(default=None)),
                ('saving_intelligence', models.BooleanField(default=None)),
                ('saving_wisdom', models.BooleanField(default=None)),
                ('saving_charisma', models.BooleanField(default=None)),
                ('acrobatics', models.BooleanField(default=None)),
                ('medicine', models.BooleanField(default=None)),
                ('animalHandling', models.BooleanField(default=None)),
                ('nature', models.BooleanField(default=None)),
                ('arcana', models.BooleanField(default=None)),
                ('perception', models.BooleanField(default=None)),
                ('athletics', models.BooleanField(default=None)),
                ('performance', models.BooleanField(default=None)),
                ('deception', models.BooleanField(default=None)),
                ('persuasion', models.BooleanField(default=None)),
                ('history', models.BooleanField(default=None)),
                ('religion', models.BooleanField(default=None)),
                ('insight', models.BooleanField(default=None)),
                ('sleightOfHand', models.BooleanField(default=None)),
                ('intimidation', models.BooleanField(default=None)),
                ('stealth', models.BooleanField(default=None)),
                ('investigation', models.BooleanField(default=None)),
                ('survival', models.BooleanField(default=None)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
            ],
        ),
    ]
