# Generated by Django 4.0.4 on 2022-07-01 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0009_alter_proficiencies_acrobatics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('type', models.IntegerField(choices=[(0, 'Simple Melee'), (1, 'Simple Ranged'), (2, 'Martial Melee'), (3, 'Martial Ranged')])),
                ('ability', models.IntegerField(choices=[(0, 'Strenght'), (1, 'Dexterity'), (2, 'Constitution'), (3, 'Intelligence'), (3, 'Wisdom'), (4, 'Charisma')])),
                ('attackBonus', models.IntegerField(default=0)),
                ('damage', models.CharField(default='1 D4', max_length=50)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
            ],
        ),
    ]
