# Generated by Django 4.0.4 on 2022-07-01 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0010_weapon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='equipment',
        ),
        migrations.AlterField(
            model_name='weapon',
            name='ability',
            field=models.IntegerField(choices=[(0, 'Strength'), (1, 'Dexterity'), (2, 'Constitution'), (3, 'Intelligence'), (4, 'Wisdom'), (5, 'Charisma')]),
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
            ],
        ),
    ]
