# Generated by Django 4.0.4 on 2022-07-08 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0012_abilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
