# Generated by Django 4.0.4 on 2022-05-31 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0005_friendship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
