# Generated by Django 4.0.4 on 2022-06-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0006_remove_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.ImageField(default=None, null=True, upload_to='static/images/'),
        ),
    ]
