# Generated by Django 4.0.4 on 2022-06-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0009_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
