# Generated by Django 4.0.4 on 2022-06-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0010_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/'),
        ),
    ]
