# Generated by Django 4.0.4 on 2022-06-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0013_alter_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.FileField(default=None, null=True, upload_to='images/'),
        ),
    ]
