# Generated by Django 4.0.4 on 2022-06-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0014_alter_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='/static/images/logo.png', null=True, upload_to='images/'),
        ),
    ]
