# Generated by Django 4.0.4 on 2022-06-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0020_alter_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, default='/static/images/download.png', upload_to='images/'),
        ),
    ]
