# Generated by Django 4.0.4 on 2022-06-08 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0021_alter_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='user1',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='utente_richiesta', to='dnd.profile'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='user2',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='utente_accettazione', to='dnd.profile'),
        ),
    ]
