# Generated by Django 4.0.4 on 2022-06-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
        ('dnd', '0024_alter_friendship_user1_alter_friendship_user2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='characters',
            field=models.ManyToManyField(default=None, to='characters.character'),
        ),
        migrations.DeleteModel(
            name='Character',
        ),
    ]
