# Generated by Django 4.0.4 on 2022-06-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0025_alter_campaign_characters_delete_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, default='images/download.png', upload_to='images/'),
        ),
    ]
