# Generated by Django 4.0.4 on 2022-07-04 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0026_alter_profile_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Campaign',
        ),
    ]
