# Generated by Django 4.0.4 on 2022-07-08 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0027_delete_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
