# Generated by Django 4.0.4 on 2022-07-04 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0012_abilities'),
        ('dnd', '0027_delete_campaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('characters', models.ManyToManyField(default=None, to='characters.character')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd.profile')),
            ],
        ),
    ]
