# Generated by Django 4.0.4 on 2022-07-06 02:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_comment_post_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.date(2022, 7, 6)),
        ),
    ]
