# Generated by Django 4.0.4 on 2022-07-06 02:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 6, 2, 32, 56, 712804, tzinfo=utc)),
        ),
    ]
