# Generated by Django 4.0.4 on 2022-07-06 04:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0027_delete_campaign'),
        ('campaigns', '0005_post_downvote_post_upvote_alter_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='character',
        ),
        migrations.AddField(
            model_name='comment',
            name='Profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='dnd.profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 6, 4, 20, 23, 101222, tzinfo=utc)),
        ),
    ]
