# Generated by Django 4.0.4 on 2022-07-07 15:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_remove_post_comments_comment_post_alter_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 7, 15, 38, 2, 359766, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 7, 15, 38, 2, 358769, tzinfo=utc)),
        ),
    ]
