# Generated by Django 4.0.4 on 2022-07-07 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_comment_time_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 7, 18, 54, 20, 360724)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 7, 18, 54, 20, 360724)),
        ),
    ]
